In [3]:
import numpy as np

arr = np.array([[10, 20, 30, 40],[50,60,70,80],[20,40,60,80]])

print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)

(3, 4)
12
2
int64


In [4]:
a=[[30,40,40],[40,30,10]]
arr=np.array(a)
print(arr)
print(arr.shape)
print(len(arr))
print(np.size(arr))
print(type(arr))
print(arr.dtype)
print(arr.astype(int))

[[30 40 40]
 [40 30 10]]
(2, 3)
2
6
<class 'numpy.ndarray'>
int64
[[30 40 40]
 [40 30 10]]


In [5]:
import numpy as np
arr1=np.array([[30,40],[20,10]])
arr2=np.array([[30,20],[10,20]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[60 60]
 [30 30]]
[[60 60]
 [30 30]]


In [6]:
arr1=np.array([9, 16,  4 , 1])
print(np.sqrt(arr1))

[3. 4. 2. 1.]


In [7]:
arr1=np.array([3,4,2,1])
arr2=np.array([2])
print(np.power(arr1,arr2))

[ 9 16  4  1]


In [8]:

import numpy as np
arr1=np.array([[30,40],[20,10]])
arr2=np.array([[30,20],[10,20]])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[1.  2. ]
 [2.  0.5]]
[[1.  2. ]
 [2.  0.5]]


In [9]:

import numpy as np
arr1=np.array([[30,40],[20,10]])
arr2=np.array([[30,20],[10,20]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[900 800]
 [200 200]]
[[900 800]
 [200 200]]


In [10]:

import numpy as np
arr1=np.array([[30,40],[20,10]])
arr2=np.array([[30,20],[10,20]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[  0  20]
 [ 10 -10]]
[[  0  20]
 [ 10 -10]]
